### PR TITLE
Introduce static analysis + Fixes

### PR DESCRIPTION
**Pull request by szepeviktor**
[Larastan](https://github.com/nunomaduro/larastan) works based on types.
From Level 4 up it will tell you many kinds of problems.

@pionl Please consider using it in CI.

`vendor/bin/phpstan analyze -c vendor/nunomaduro/larastan/extension.neon -l 4 src/`
all the way up to Level max.

powered by @phpstan

### CODE REVIEW

**Comment by pionl** [comment]
Thank you again for your contribution! I've update the code to match the report + also it will run in CI (had to drop 7.1).

Are the changes OK at your end? https://github.com/pionl/laravel-chunk-upload/tree/sharpstream-sharpstream

**Comment by szepeviktor** [comment]
You're welcome.

**Comment by szepeviktor** [comment]
Did you know you can add commit to my PR?

**Comment by pionl** [comment]
> Did you know you can add commits to my PR?

I tried to push commits in different repo and it didn't work -- will check next time. Thanks for the heads up

**Pull request closed without merging**
