### PR TITLE
Add support for Request with multiple files array

### PR DESCRIPTION
**Pull request by RAZORzdenko**
- FileReceiver constructor now has new optional parameter - int $fileArrayIndex. $fileArrayIndex expects index of file in file array.

### CODE REVIEW

**Comment by pionl** [comment]
Hi @RAZORzdenko , thank you for the proposal, but you should be able to set it via key. Could you try this? `file.0` or `file.1`.

Thank you

**Comment by RAZORzdenko** [comment]
I don't think I can do that as everywhere I need to send Request, not a file. Here's my code that I use with modification I made.

```
    foreach($request['position'] as $index => $pos) {
      Item::create([
        'file_path' => $this->uploadFile($request, Item::$uploadProperties, $request->inputName, $index)
      ]);
    }
```

```
  public function uploadFile ($request, $uploadProperties, $inputName, $fileIndex = null)
  {
    $receiver = new FileReceiver($inputName, $request, ContentRangeUploadHandler::class, null, null, $fileIndex);
    ....
  }
```

**Comment by pionl** [comment]
Thank you for the code. I would try this change:

```php
 public function uploadFile ($request, $uploadProperties, $inputName, $fileIndex = null)
  {
    $receiver = new FileReceiver("{$inputName}.{$fileIndex}", $request, ContentRangeUploadHandler::class);
    ....
  }
```

This will usage helps to leverage already existing usage of `data_get` function which supports accessing an array with dot anotation.

**Comment by RAZORzdenko** [comment]
Had no idea this existed but unfortunately this doesn't work and throws UploadMissingFileException.

**Comment by pionl** [comment]
Ok, thank you for the quick test. I think it would be much easier to make this change because of the arguments order (the file index will be last - not so easy to use). Can you make the change? Will merge then.

Thank you for the support/contribution!

```php
/**
     * The file receiver for the given file index
     *
     * @param string|UploadedFile              $fileIndexOrFile the desired file index to use in request or the final UploadedFile
     * @param Request             $request the current request
     * @param string              $handlerClass the handler class name for detecting the file upload
     * @param ChunkStorage|null   $chunkStorage the chunk storage, on null will use the instance from app container
     * @param AbstractConfig|null $config the config, on null will use the instance from app container
     */
    public function __construct($fileIndexOrFile, Request $request, $handlerClass, $chunkStorage = null, $config = null)
    {
        $this->request = $request;
        $this->file = is_object($fileIndexOrFile) ? $fileIndexOrFile : $request->file($fileIndex);
        $this->chunkStorage = is_null($chunkStorage) ? ChunkStorage::storage() : $chunkStorage;
        $this->config = is_null($config) ? AbstractConfig::config() : $config;
        if ($this->isUploaded()) {
            $this->handler = new $handlerClass($this->request, $this->file, $this->config);
        }
    }
```

**Comment by pionl** [comment]
Then just call
```php
 public function uploadFile ($request, $uploadProperties, $inputName, $fileIndex = null)
  {
// Get the file array
$file = $request->file(inputName);
if (!is_null($fileIndex) && is_array($file)) {
// When not found in array, will return null
$file = array_get($fileArray, $fileIndex);
}
    $receiver = new FileReceiver($file, $request, ContentRangeUploadHandler::class, null, null, $fileIndex);
    ....
  }
```

**Comment by RAZORzdenko** [comment]
Thank you very much for help. I just pushed new commit with these changes and updated readme.

**Comment by pionl** [comment]
@RAZORzdenko Thank you for the the changes, I had rebased the commits to fewer changes (updated the php-docs that was missing + also updated the realm change to use easier example).

Thank you for the changes and contribution. If there is anything missing, just let me know and we can make the changes together.

**Pull request closed without merging**
