### PR TITLE
Update dependencies for Laravel 5.5.

### PR DESCRIPTION
**Pull request by Colbydude**
Not fully tested in a project yet, but all tests are passing with the updated dependencies.

### CODE REVIEW

**Comment by Colbydude** [comment]
Travis build fails due to Laravel 5.5 requiring PHP 7.0.

**Comment by pionl** [comment]
Hi @Colbydude,

thank you for the info. You can remove the 5.6 from `.travis.yml` to fix this issue. In near future I will try to setup travis to build older php version and laravel versions.

I've read the upgrade guide and I've noticed, that the `files` method has changed and returns `SplFileInfo` instead of string. In [ChunkStorage](https://github.com/pionl/laravel-chunk-upload/blob/master/src/Storage/ChunkStorage.php#L113) there is listing of files and `oldChunkFiles` is then iterating the files listen in the directory. It requires a string. But it seems that `SplFileInfo` has implemented __toString and it should work.

Could you confirm that it's working? Ensure that there is a file. (just run the `php artisan uploads:clear`). Or you can create a unit test for this part (which would be great, the tests are just starting to be implemented).

Martin

**Comment by Colbydude** [comment]
Double checked and ChunkStorage is iterating through the files correctly.

Removed 5.6 from Travis and it should be good to go. 👌🏻

**Comment by pionl** [comment]
Thanks @Colbydude for the work, later I will update the example repo and tests it my self 👍

**Pull request merged**
