### PR TITLE
Add GitWorkflow

### PR DESCRIPTION
**Pull request by klimov-paul**
* switch to GitHub actions
* add Laravel 9 support

### CODE REVIEW

**Comment by pionl** [comment]
Hi @klimov-paul Thanks! Did you try it? The filesystem drivers has changed so it is possible it will "crash". Here is an ability to test it via integration tests https://github.com/pionl/laravel-chunk-upload-example

**Comment by klimov-paul** [comment]
No, I did not yet.

**Comment by pionl** [comment]
Kk il try to find some time this weekend and test your PR. Thank you for the templates / GitWorflows!

**Review by pionl — APPROVED** [review]
perfect, thanks! PR with Laravel 9 support has landed. Merging.

**Pull request closed without merging**
