### PR TITLE
please merge this PR

### PR DESCRIPTION
**Pull request by MahdiPishguy**
could you please merge this repository and pull request?

### CODE REVIEW

**Comment by parallela** [comment]
+1

**Comment by wimil** [comment]
+1

**Comment by s1rc** [comment]
+1

**Comment by pionl** [comment]
🚀 Laravel 8 support in 1.4.1 added - all acceptance tests passed

**Comment by thomascombe** [comment]
Just missing a [README.md](https://github.com/pionl/laravel-chunk-upload#compatibility) update

**Pull request closed without merging**
