### PR TITLE
Support for resumable uploads

### LINKED ISSUE #10: What's your recommendation to resumable uploads with this package?
Hi,

thanks for this amazing package. Saved me tons of time, but I have been wondering about implementing a resumable upload option. What's your recommendation to resumable uploads with this package?

Would love to hear it :-)

### PR DESCRIPTION
**Pull request by nerg4l**
This resolves #10 

I welcome any recommendation about my code.

### CODE REVIEW

**Comment by pionl** [comment]
What the state? Is it implemented?

**Comment by nerg4l** [comment]
I did not have time yesterday to resolve the conflicts. Despite that it is finished.

**Comment by pionl** [comment]
ok, I can make resolve conflicts when I have free time. Is there any necessary js changes I need to make? (to test the feature)

**Comment by nerg4l** [comment]
## [23/resumable.js](https://github.com/23/resumable.js)

Enable `testChunks`

You can find a detailed description about the property [here](https://github.com/23/resumable.js#handling-get-or-test-requests).

The point is, it will send a `GET` request to the same url where it sends the `POST`. 

## [blueimp/jQuery-File-Upload](https://github.com/blueimp/jQuery-File-Upload)

```
$('#fileupload').fileupload({
    maxChunkSize: 10000000, // 10 MB
    add: function (e, data) {
        var that = this;
        var f = data.files[0];
        $.getJSON('server/php/', {file: f.name, size: f.size}, function (result) {
            data.uploadedBytes = result.size;
            $.blueimp.fileupload.prototype
                .options.add.call(that, e, data);
        });
    }
});
```

A simmilar example can be found [here](https://github.com/blueimp/jQuery-File-Upload/wiki/Chunked-file-uploads#resuming-file-uploads), the difference is you have pass the size of the file, because it is used by the handler to create a unique filename and also the size property is in the base response not under a file property.

## [simple-uploader/Uploader](https://github.com/simple-uploader/Uploader)

This is really simmilar to `23/resumable.js` as you can see [here](https://github.com/simple-uploader/Uploader#handling-get-or-test-requests). And according to the documentation both treats `204 No content` response the same way. Only the name of the parameters are changed.

## [danialfarid/ng-file-upload](https://github.com/danialfarid/ng-file-upload)

It has a `resumeSizeUrl` property. You can find an example [here](https://github.com/danialfarid/ng-file-upload#upload-service).

Same thing applies here as on `jQuery-File-Upload`, which means you have to pass the size too, not just the filename.

```
resumeSizeUrl: '/uploaded/size/url?file=' + file.name + '&size=' + file.size
```

**Comment by nerg4l** [comment]
The way I implemented the HandlerFactory isn't the best. I'll think about a better way. If you have an idea or suggestion I would appreciate it.

**Comment by mattogodoy** [comment]
Hi! I'm very interested in this functionality.

Are there any news about this merge request?
Thanks!

**Comment by rluders** [comment]
I'm also interested in this feature.

**Comment by mattogodoy** [comment]
@rluders I made a temporary solution that is working with no issues:
https://github.com/pionl/laravel-chunk-upload/issues/10#issuecomment-448615836

**Comment by pionl** [comment]
Hi @nerg4l, should I find the time to check your feature? Did you finally use it in production?

**Comment by nerg4l** [comment]
This implementation is very hacky and I decided to ditch it. With the current logic of the request handling it is really hard to distinguish between the frontend libraries when the norm of this library is it relies on the parameters/headers.

I started working on a different implementation to make it simpler with [using drivers](https://github.com/LaraCrafts/laravel-chunk-uploader/blob/master/config/chunk-uploader.php#L48-L57). My current work is available here: https://github.com/LaraCrafts/laravel-chunk-uploader

**Comment by pionl** [comment]
I see you improved the ideas -- the separation between handle / saver is not ideal.

**Pull request closed without merging**
