### PR TITLE
Update package for laravel 7.0 support, breaking support for older

### PR DESCRIPTION
**Pull request by drjdr**

### CODE REVIEW

**Comment by pionl** [comment]
Hi,

- squash commits please
- remove custom packagist - still you do not need to do it - you can use repositories in your composer project

Thanks

**Comment by pionl** [comment]
Also you have removed the support for older versions of laravel wich should be still supported. Can you chceck laravel version and return your implemenzation only for 7.0+?

Thanks

**Comment by pionl** [comment]
Thank you for the changes, but still I think we should support older version (at this moment there is only one change needed). I can improve the code you provided to support all version.

At this moment I'm creating automatic tests that should help me to make decisions when updating app to newer version (less time consuming for me -- I should be able to do it).

Should be completed in 2 days.

WIP: https://github.com/pionl/laravel-chunk-upload-example/tree/multiple-laravel-versions

**Comment by drjdr** [comment]
Cool, Thanks Martin.

**Comment by pionl** [comment]
I've rebased the changes to single commit - I've fixed a small bug (you have changed the composer.json name, it gave me small headache why composer require does not work :D ). Thanks for the find and docs improvements 💪.

Here is the new pull request https://github.com/pionl/laravel-chunk-upload/pull/107

**Pull request closed without merging**
